<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-02T07:34:42+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Herran Bread',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1452866320,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.6',
        'favicon_fid' => '1',
        'login_redirect' => 'HOMEPAGE',
        'login_redirect_cid' => 0,
        'login_admin_to_dashboard' => 0,
    ),
    'accessibility' => array(
        'toolbar_titles' => false,
        'toolbar_large_font' => false,
        'display_help_system' => false,
    ),
);
